// export const data = [
//   {
//     image:
//       "https://www.shutterstock.com/image-photo/desktop-computer-keyboard-mouse-on-100nw-164253011.jpg",
//     brand: "Samung",
//     price: "$1,400,000",
//     sale: "15%",
//     caticory: "Гал тогоо",
//     date: "2020.02.22",
//     order: "#1583",
//     number: "99110100",
//     email: "qwe@gmail.com",
//     num: "3",
//     pay: "kartaaр",
//     status: "active",
//     sureName: "Улаанбанди",
//     firstName: "Юнчир",
//     address: "БЗД 22-хороо...",
//   },
//   {
//     image:
//       "https://www.shutterstock.com/image-photo/desktop-computer-keyboard-mouse-on-100nw-164253011.jpg",
//     brand: "Samung",
//     price: "$1,400,000",
//     sale: "15%",
//     caticory: "Гал тогоо",
//     date: "2020.02.22",
//     order: "#1583",
//     number: "99110100",
//     email: "qwe@gmail.com",
//     num: "3",
//     pay: "kartaaр",
//     status: "active",
//     sureName: "Улаанбанди",
//     firstName: "Юнчир",
//     address: "БЗД 22-хороо...",
//   },
//   {
//     image:
//       "https://www.shutterstock.com/image-photo/desktop-computer-keyboard-mouse-on-100nw-164253011.jpg",
//     brand: "Samung",
//     price: "$1,400,000",
//     sale: "15%",
//     caticory: "Гал тогоо",
//     date: "2020.02.22",
//     order: "#1583",
//     number: "99110100",
//     email: "qwe@gmail.com",
//     num: "3",
//     pay: "kartaaр",
//     status: "active",
//     sureName: "Улаанбанди",
//     firstName: "Юнчир",
//     address: "БЗД 22-хороо...",
//   },
//   {
//     image:
//       "https://www.shutterstock.com/image-photo/desktop-computer-keyboard-mouse-on-100nw-164253011.jpg",
//     brand: "Samung",
//     price: "$1,400,000",
//     sale: "15%",
//     caticory: "Гал тогоо",
//     date: "2020.02.22",
//     order: "#1583",
//     number: "99110100",
//     email: "qwe@gmail.com",
//     num: "3",
//     pay: "kartaaр",
//     status: "active",
//     sureName: "Улаанбанди",
//     firstName: "Юнчир",
//     address: "БЗД 22-хороо...",
//   },
//   {
//     image:
//       "https://www.shutterstock.com/image-photo/desktop-computer-keyboard-mouse-on-100nw-164253011.jpg",
//     brand: "Samung",
//     price: "$1,400,000",
//     sale: "15%",
//     caticory: "Гал тогоо",
//     date: "2020.02.22",
//     order: "#1583",
//     number: "99110100",
//     email: "qwe@gmail.com",
//     num: "3",
//     pay: "kartaaр",
//     status: "active",
//     sureName: "Улаанбанди",
//     firstName: "Юнчир",
//     address: "БЗД 22-хороо...",
//   },
//   {
//     image:
//       "https://www.shutterstock.com/image-photo/desktop-computer-keyboard-mouse-on-100nw-164253011.jpg",
//     brand: "Samung",
//     price: "$1,400,000",
//     sale: "15%",
//     caticory: "Гал тогоо",
//     date: "2020.02.22",
//     order: "#1583",
//     number: "99110100",
//     email: "qwe@gmail.com",
//     num: "3",
//     pay: "kartaaр",
//     status: "active",
//     sureName: "Улаанбанди",
//     firstName: "Юнчир",
//     address: "БЗД 22-хороо...",
//   },
//   {
//     image:
//       "https://www.shutterstock.com/image-photo/desktop-computer-keyboard-mouse-on-100nw-164253011.jpg",
//     brand: "Samung",
//     price: "$1,400,000",
//     sale: "15%",
//     caticory: "Гал тогоо",
//     date: "2020.02.22",
//     order: "#1583",
//     number: "99110100",
//     email: "qwe@gmail.com",
//     num: "3",
//     pay: "kartaaр",
//     status: "active",
//     sureName: "Улаанбанди",
//     firstName: "Юнчир",
//     address: "БЗД 22-хороо...",
//   },
//   {
//     image:
//       "https://www.shutterstock.com/image-photo/desktop-computer-keyboard-mouse-on-100nw-164253011.jpg",
//     brand: "Samung",
//     price: "$1,400,000",
//     sale: "15%",
//     caticory: "Гал тогоо",
//     date: "2020.02.22",
//     order: "#1583",
//     number: "99110100",
//     email: "qwe@gmail.com",
//     num: "3",
//     pay: "kartaaр",
//     status: "active",
//     sureName: "Улаанбанди",
//     firstName: "Юнчир",
//     address: "БЗД 22-хороо...",
//   },
// ];
